require "./setup"
tp Magick.formats

# to_blob は write と同等ではなく * を含むものだけをサポートしている
tp Magick.formats.find_all { |k, v| v.start_with?("*") }.to_h

# >> |-----------------+------|
# >> |             3FR |  r-+ |
# >> |             3G2 |  r-+ |
# >> |             3GP |  r-+ |
# >> |             AAI | *rw+ |
# >> |              AI |  rw- |
# >> |            APNG |  rw+ |
# >> |             ART | *rw- |
# >> |             ARW |  r-+ |
# >> |          ASHLAR | *-w+ |
# >> |             AVI |  r-+ |
# >> |            AVIF | *rw+ |
# >> |             AVS | *rw+ |
# >> |             BGR | *rw+ |
# >> |            BGRA | *rw+ |
# >> |            BGRO | *rw+ |
# >> |             BMP | *rw- |
# >> |            BMP2 | *rw- |
# >> |            BMP3 | *rw- |
# >> |             BRF | *-w- |
# >> |             CAL | *rw- |
# >> |            CALS | *rw- |
# >> |          CANVAS | *r-- |
# >> |         CAPTION | *r-- |
# >> |             CIN | *rw- |
# >> |             CIP | *-w- |
# >> |            CLIP | *rw+ |
# >> |            CMYK | *rw+ |
# >> |           CMYKA | *rw+ |
# >> |             CR2 |  r-+ |
# >> |             CR3 |  r-+ |
# >> |             CRW |  r-+ |
# >> |            CUBE | *r-- |
# >> |             CUR | *rw- |
# >> |             CUT | *r-+ |
# >> |            DATA | *rw+ |
# >> |             DCM | *r-- |
# >> |             DCR |  r-+ |
# >> |           DCRAW |  r-+ |
# >> |             DCX | *rw+ |
# >> |             DDS | *rw+ |
# >> |           DFONT | *r-- |
# >> |             DNG |  r-+ |
# >> |             DOT |  --+ |
# >> |             DPX | *rw- |
# >> |            DXT1 | *rw+ |
# >> |            DXT5 | *rw+ |
# >> |            EPDF |  rw- |
# >> |             EPI |  rw- |
# >> |             EPS |  rw- |
# >> |            EPS2 |  -w- |
# >> |            EPS3 |  -w+ |
# >> |            EPSF |  rw- |
# >> |            EPSI |  rw- |
# >> |             EPT |  rw- |
# >> |            EPT2 |  rw- |
# >> |            EPT3 |  rw+ |
# >> |             ERF |  r-+ |
# >> |             EXR |  rw- |
# >> |        FARBFELD | *rw- |
# >> |             FAX | *rw+ |
# >> |              FF | *rw- |
# >> |            FILE | *r-+ |
# >> |            FITS | *rw- |
# >> |            FL32 | *rw- |
# >> |             FLV |  rw+ |
# >> |         FRACTAL | *r-- |
# >> |             FTP | *r-+ |
# >> |             FTS | *rw- |
# >> |              G3 | *rw- |
# >> |              G4 | *rw- |
# >> |             GIF | *rw+ |
# >> |           GIF87 | *rw- |
# >> |        GRADIENT | *r-- |
# >> |            GRAY | *rw+ |
# >> |           GRAYA | *rw+ |
# >> |          GROUP4 | *rw- |
# >> |              GV |  --+ |
# >> |            HALD | *r-- |
# >> |             HDR | *rw+ |
# >> |            HEIC | *rw+ |
# >> |            HEIF | *rw+ |
# >> |       HISTOGRAM | *-w- |
# >> |             HRZ | *rw- |
# >> |             HTM | *-w- |
# >> |            HTML | *-w- |
# >> |            HTTP | *r-+ |
# >> |           HTTPS | *r-+ |
# >> |             ICB | *rw- |
# >> |             ICO | *rw+ |
# >> |            ICON | *rw- |
# >> |             IIQ |  r-+ |
# >> |            INFO |  -w+ |
# >> |          INLINE | *rw+ |
# >> |             IPL | *rw+ |
# >> |          ISOBRL | *-w- |
# >> |         ISOBRL6 | *-w- |
# >> |             J2C | *rw- |
# >> |             J2K | *rw- |
# >> |             JNG | *rw- |
# >> |             JNX | *r-+ |
# >> |             JP2 | *rw- |
# >> |             JPC | *rw- |
# >> |             JPE | *rw- |
# >> |            JPEG | *rw- |
# >> |             JPG | *rw- |
# >> |             JPM | *rw- |
# >> |             JPS | *rw- |
# >> |             JPT | *rw- |
# >> |            JSON |  -w+ |
# >> |             K25 |  r-+ |
# >> |             KDC |  r-+ |
# >> |          KERNEL | *-w- |
# >> |           LABEL | *r-- |
# >> |             M2V |  rw+ |
# >> |             M4V |  rw+ |
# >> |             MAC | *r-+ |
# >> |             MAP | *rw- |
# >> |            MASK | *rw+ |
# >> |             MAT |  rw+ |
# >> |           MATTE | *-w+ |
# >> |             MEF |  r-+ |
# >> |            MIFF | *rw+ |
# >> |             MKV |  rw+ |
# >> |             MNG | *rw+ |
# >> |            MONO | *rw- |
# >> |             MOV |  rw+ |
# >> |             MP4 |  rw+ |
# >> |             MPC | *rw+ |
# >> |            MPEG |  rw+ |
# >> |             MPG |  rw+ |
# >> |             MRW |  r-+ |
# >> |             MSL | *rw+ |
# >> |            MSVG | *rw+ |
# >> |             MTV | *rw+ |
# >> |             MVG | *rw- |
# >> |             NEF |  r-+ |
# >> |             NRW |  r-+ |
# >> |            NULL | *rw- |
# >> |             ORA |  --+ |
# >> |             ORF |  r-+ |
# >> |             OTB | *rw- |
# >> |             OTF | *r-- |
# >> |             PAL | *rw- |
# >> |            PALM | *rw+ |
# >> |             PAM | *rw+ |
# >> |           PANGO | *--- |
# >> |         PATTERN | *r-- |
# >> |             PBM | *rw+ |
# >> |             PCD | *rw- |
# >> |            PCDS | *rw- |
# >> |             PCL |  rw+ |
# >> |             PCT | *rw- |
# >> |             PCX | *rw- |
# >> |             PDB | *rw+ |
# >> |             PDF |  rw+ |
# >> |            PDFA |  rw+ |
# >> |             PEF |  r-+ |
# >> |             PES | *r-+ |
# >> |             PFA | *r-- |
# >> |             PFB | *r-- |
# >> |             PFM | *rw+ |
# >> |             PGM | *rw+ |
# >> |             PGX | *rw- |
# >> |             PHM | *rw+ |
# >> |           PICON | *rw- |
# >> |            PICT | *rw- |
# >> |             PIX | *r-+ |
# >> |           PJPEG | *rw- |
# >> |          PLASMA | *r-- |
# >> |             PNG | *rw- |
# >> |           PNG00 | *rw- |
# >> |           PNG24 | *rw- |
# >> |           PNG32 | *rw- |
# >> |           PNG48 | *rw- |
# >> |           PNG64 | *rw- |
# >> |            PNG8 | *rw- |
# >> |             PNM | *rw+ |
# >> |       POCKETMOD |  rw+ |
# >> |             PPM | *rw+ |
# >> |              PS |  rw+ |
# >> |             PS2 |  -w+ |
# >> |             PS3 |  -w+ |
# >> |             PSB | *rw+ |
# >> |             PSD | *rw+ |
# >> |            PTIF | *rw+ |
# >> |             PWP | *r-+ |
# >> | RADIAL-GRADIENT | *r-- |
# >> |             RAF |  r-+ |
# >> |             RAS | *rw+ |
# >> |             RAW |  r-+ |
# >> |             RGB | *rw+ |
# >> |          RGB565 | *r-+ |
# >> |            RGBA | *rw+ |
# >> |            RGBO | *rw+ |
# >> |             RGF | *rw- |
# >> |             RLA | *r-- |
# >> |             RLE | *r-- |
# >> |             RMF |  r-+ |
# >> |             RW2 |  r-+ |
# >> |             SCR | *r-- |
# >> |             SCT | *r-- |
# >> |             SFW | *r-- |
# >> |             SGI | *rw+ |
# >> |           SHTML | *-w- |
# >> |             SIX | *rw- |
# >> |           SIXEL | *rw- |
# >> |    SPARSE-COLOR | *-w+ |
# >> |             SR2 |  r-+ |
# >> |             SRF |  r-+ |
# >> |         STEGANO | *r-+ |
# >> |             SUN | *rw+ |
# >> |             SVG | *rw+ |
# >> |            SVGZ | *rw+ |
# >> |            TEXT | *r-+ |
# >> |             TGA | *rw- |
# >> |       THUMBNAIL | *-w+ |
# >> |            TIFF | *rw+ |
# >> |          TIFF64 | *rw+ |
# >> |            TILE | *r-+ |
# >> |             TIM | *r-+ |
# >> |             TM2 | *r-+ |
# >> |             TTC | *r-- |
# >> |             TTF | *r-- |
# >> |             TXT | *rw+ |
# >> |            UBRL | *-w- |
# >> |           UBRL6 | *-w- |
# >> |             UIL | *-w- |
# >> |            UYVY | *rw- |
# >> |             VDA | *rw- |
# >> |           VICAR | *rw- |
# >> |             VID | *rw+ |
# >> |            VIFF | *rw+ |
# >> |            VIPS | *rw+ |
# >> |             VST | *rw- |
# >> |            WBMP | *rw- |
# >> |            WEBM |  rw+ |
# >> |            WEBP | *rw+ |
# >> |             WMV |  rw+ |
# >> |             WPG | *r-+ |
# >> |             X3F |  r-+ |
# >> |             XBM | *rw- |
# >> |              XC | *r-- |
# >> |             XCF | *r-+ |
# >> |             XPM | *rw- |
# >> |             XPS |  r-- |
# >> |              XV | *rw+ |
# >> |            YAML |  -w+ |
# >> |           YCbCr | *rw+ |
# >> |          YCbCrA | *rw+ |
# >> |             YUV | *rw- |
# >> |-----------------+------|
# >> |-----------------+------|
# >> |             AAI | *rw+ |
# >> |             ART | *rw- |
# >> |          ASHLAR | *-w+ |
# >> |            AVIF | *rw+ |
# >> |             AVS | *rw+ |
# >> |             BGR | *rw+ |
# >> |            BGRA | *rw+ |
# >> |            BGRO | *rw+ |
# >> |             BMP | *rw- |
# >> |            BMP2 | *rw- |
# >> |            BMP3 | *rw- |
# >> |             BRF | *-w- |
# >> |             CAL | *rw- |
# >> |            CALS | *rw- |
# >> |          CANVAS | *r-- |
# >> |         CAPTION | *r-- |
# >> |             CIN | *rw- |
# >> |             CIP | *-w- |
# >> |            CLIP | *rw+ |
# >> |            CMYK | *rw+ |
# >> |           CMYKA | *rw+ |
# >> |            CUBE | *r-- |
# >> |             CUR | *rw- |
# >> |             CUT | *r-+ |
# >> |            DATA | *rw+ |
# >> |             DCM | *r-- |
# >> |             DCX | *rw+ |
# >> |             DDS | *rw+ |
# >> |           DFONT | *r-- |
# >> |             DPX | *rw- |
# >> |            DXT1 | *rw+ |
# >> |            DXT5 | *rw+ |
# >> |        FARBFELD | *rw- |
# >> |             FAX | *rw+ |
# >> |              FF | *rw- |
# >> |            FILE | *r-+ |
# >> |            FITS | *rw- |
# >> |            FL32 | *rw- |
# >> |         FRACTAL | *r-- |
# >> |             FTP | *r-+ |
# >> |             FTS | *rw- |
# >> |              G3 | *rw- |
# >> |              G4 | *rw- |
# >> |             GIF | *rw+ |
# >> |           GIF87 | *rw- |
# >> |        GRADIENT | *r-- |
# >> |            GRAY | *rw+ |
# >> |           GRAYA | *rw+ |
# >> |          GROUP4 | *rw- |
# >> |            HALD | *r-- |
# >> |             HDR | *rw+ |
# >> |            HEIC | *rw+ |
# >> |            HEIF | *rw+ |
# >> |       HISTOGRAM | *-w- |
# >> |             HRZ | *rw- |
# >> |             HTM | *-w- |
# >> |            HTML | *-w- |
# >> |            HTTP | *r-+ |
# >> |           HTTPS | *r-+ |
# >> |             ICB | *rw- |
# >> |             ICO | *rw+ |
# >> |            ICON | *rw- |
# >> |          INLINE | *rw+ |
# >> |             IPL | *rw+ |
# >> |          ISOBRL | *-w- |
# >> |         ISOBRL6 | *-w- |
# >> |             J2C | *rw- |
# >> |             J2K | *rw- |
# >> |             JNG | *rw- |
# >> |             JNX | *r-+ |
# >> |             JP2 | *rw- |
# >> |             JPC | *rw- |
# >> |             JPE | *rw- |
# >> |            JPEG | *rw- |
# >> |             JPG | *rw- |
# >> |             JPM | *rw- |
# >> |             JPS | *rw- |
# >> |             JPT | *rw- |
# >> |          KERNEL | *-w- |
# >> |           LABEL | *r-- |
# >> |             MAC | *r-+ |
# >> |             MAP | *rw- |
# >> |            MASK | *rw+ |
# >> |           MATTE | *-w+ |
# >> |            MIFF | *rw+ |
# >> |             MNG | *rw+ |
# >> |            MONO | *rw- |
# >> |             MPC | *rw+ |
# >> |             MSL | *rw+ |
# >> |            MSVG | *rw+ |
# >> |             MTV | *rw+ |
# >> |             MVG | *rw- |
# >> |            NULL | *rw- |
# >> |             OTB | *rw- |
# >> |             OTF | *r-- |
# >> |             PAL | *rw- |
# >> |            PALM | *rw+ |
# >> |             PAM | *rw+ |
# >> |           PANGO | *--- |
# >> |         PATTERN | *r-- |
# >> |             PBM | *rw+ |
# >> |             PCD | *rw- |
# >> |            PCDS | *rw- |
# >> |             PCT | *rw- |
# >> |             PCX | *rw- |
# >> |             PDB | *rw+ |
# >> |             PES | *r-+ |
# >> |             PFA | *r-- |
# >> |             PFB | *r-- |
# >> |             PFM | *rw+ |
# >> |             PGM | *rw+ |
# >> |             PGX | *rw- |
# >> |             PHM | *rw+ |
# >> |           PICON | *rw- |
# >> |            PICT | *rw- |
# >> |             PIX | *r-+ |
# >> |           PJPEG | *rw- |
# >> |          PLASMA | *r-- |
# >> |             PNG | *rw- |
# >> |           PNG00 | *rw- |
# >> |           PNG24 | *rw- |
# >> |           PNG32 | *rw- |
# >> |           PNG48 | *rw- |
# >> |           PNG64 | *rw- |
# >> |            PNG8 | *rw- |
# >> |             PNM | *rw+ |
# >> |             PPM | *rw+ |
# >> |             PSB | *rw+ |
# >> |             PSD | *rw+ |
# >> |            PTIF | *rw+ |
# >> |             PWP | *r-+ |
# >> | RADIAL-GRADIENT | *r-- |
# >> |             RAS | *rw+ |
# >> |             RGB | *rw+ |
# >> |          RGB565 | *r-+ |
# >> |            RGBA | *rw+ |
# >> |            RGBO | *rw+ |
# >> |             RGF | *rw- |
# >> |             RLA | *r-- |
# >> |             RLE | *r-- |
# >> |             SCR | *r-- |
# >> |             SCT | *r-- |
# >> |             SFW | *r-- |
# >> |             SGI | *rw+ |
# >> |           SHTML | *-w- |
# >> |             SIX | *rw- |
# >> |           SIXEL | *rw- |
# >> |    SPARSE-COLOR | *-w+ |
# >> |         STEGANO | *r-+ |
# >> |             SUN | *rw+ |
# >> |             SVG | *rw+ |
# >> |            SVGZ | *rw+ |
# >> |            TEXT | *r-+ |
# >> |             TGA | *rw- |
# >> |       THUMBNAIL | *-w+ |
# >> |            TIFF | *rw+ |
# >> |          TIFF64 | *rw+ |
# >> |            TILE | *r-+ |
# >> |             TIM | *r-+ |
# >> |             TM2 | *r-+ |
# >> |             TTC | *r-- |
# >> |             TTF | *r-- |
# >> |             TXT | *rw+ |
# >> |            UBRL | *-w- |
# >> |           UBRL6 | *-w- |
# >> |             UIL | *-w- |
# >> |            UYVY | *rw- |
# >> |             VDA | *rw- |
# >> |           VICAR | *rw- |
# >> |             VID | *rw+ |
# >> |            VIFF | *rw+ |
# >> |            VIPS | *rw+ |
# >> |             VST | *rw- |
# >> |            WBMP | *rw- |
# >> |            WEBP | *rw+ |
# >> |             WPG | *r-+ |
# >> |             XBM | *rw- |
# >> |              XC | *r-- |
# >> |             XCF | *r-+ |
# >> |             XPM | *rw- |
# >> |              XV | *rw+ |
# >> |           YCbCr | *rw+ |
# >> |          YCbCrA | *rw+ |
# >> |             YUV | *rw- |
# >> |-----------------+------|
